#!/bin/sh

# SAUER_OPTIONS contains any command line options you would like to start Sauerbraten with.
SAUER_OPTIONS=""

# SAUER_HOME is where Sauerbraten should store user files.
SAUER_HOME="${HOME}/Library/Application Support/Sauerbraten"

cd "$(dirname "$0")"

if [ -e "../Resources/data/stdlib.cfg" ]; then
    # we are an app package
    CONTENT_DIR="$(dirname $PWD)/Resources"
elif [ -e "../../../data/stdlib.cfg" ]; then
    # we are being run in place
    CONTENT_DIR=$PWD
    # todo: better way to walk up three levels and get an absolute path
    CONTENT_DIR=$(dirname $CONTENT_DIR)
    CONTENT_DIR=$(dirname $CONTENT_DIR)
    CONTENT_DIR=$(dirname $CONTENT_DIR)
else
    echo "cannot find content directory"
    exit 1
fi

./start_protected_game.app/Contents/MacOS/start_protected_game -e -k"${CONTENT_DIR}" -q"${SAUER_HOME}" -glog.txt ${SAUER_OPTIONS} $@
